# -*- coding: utf-8 -*-
"""UTS_AI.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1WUZoFnUbV6fhZhUyBUYcgfYMM4L4vIl-
"""

import pandas as pd

data = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9],
]

df = pd.DataFrame(data)

print(df)

import numpy as np

P1 = np.array([1, 2])
P2 = np.array([3, 4])

def euclidean_distance(point1, point2):
    return np.sqrt(np.sum((point1 - point2) ** 2))

distance = euclidean_distance(P1, P2)

print(f'Titik 1: {P1}')
print(f'Titik 2: {P2}')
print(f'Jarak Euclidean: {distance}')

from sklearn.neighbors import KNeighborsClassifier

data = [
    [1, 2, 'A'],
    [4, 5, 'B'],
    [7, 8, 'A']
]

x = [[row[0], row[1]] for row in data]
y = [row[2] for row in data]

model = KNeighborsClassifier(n_neighbors=1)
model.fit(x, y)

data_test = [
    [2, 3],
    [6, 7]
]

for point in data_test:
    prediction = model.predict([point])
    print(f'Data {point} diklasifikasikan sebagai kelas {prediction[0]}')
    print()

# Jawaban no 4 perbedaan Google Colab dan Jupyter Notebook:
 #  Google Colab:

   # Hosting oleh Google: Google Colab di-host oleh Google dan dijalankan di infrastruktur komputasi awan mereka. Penyimpanan data dan notebook utama terletak di Google Drive.

   # Resource Komputasi Gratis: Colab menyediakan sumber daya komputasi gratis, termasuk penggunaan GPU dan TPU untuk beberapa waktu komputasi.

   # Dukungan Khusus Google: Colab terintegrasi dengan layanan Google lainnya seperti Google Drive, sehingga memudahkan berbagi dan menyimpan notebook.

   # Terbatas Waktu Komputasi: Sumber daya komputasi gratis di Colab bersifat terbatas dan dapat dihentikan setelah beberapa waktu tidak aktif.

 # Jupyter Notebook:

   # Self-Hosting atau Lokal: Jupyter Notebook dapat dijalankan di mesin lokal atau di-hosted sendiri, misalnya di server atau mesin kerja.

   # Fleksibilitas Lokal atau di Cloud: Anda memiliki kendali penuh terhadap di mana dan bagaimana Jupyter Notebook dijalankan. Anda bisa menjalankannya di mesin lokal, di server internal, atau di platform cloud seperti AWS, Azure, atau Google Cloud.

   # Sumber Daya Tergantung pada Lingkungan: Jupyter Notebook di mesin lokal atau di server internal akan menggunakan sumber daya yang tersedia pada mesin tersebut.

   # Tidak Terbatas Waktu Komputasi: Di lingkungan lokal atau di server sendiri, tidak ada batasan waktu komputasi seperti yang mungkin ditemui di Google Colab.

# Jawaban no 5
   #Buka Google Colab menggunakan peramban web 
   #Untuk membuat notebook baru, klik pada tombol "New Notebook" di bagian kiri halaman atau pilih "File" > "New Notebook" dari menu.
   #Anda dapat menambahkan sel baru dengan mengeklik tombol "+ Code" atau "+ Text" di bagian atas atau bawah notebook.
   #Setelah menambahkan kode, jalankan sel dengan menekan tombol play di sebelah kiri sel atau menggunakan kombinasi tombol Shift+Enter, hasilnya akan ditampilkan di bawah sel.
   #Simpan notebook di Google Drive dengan memilih "File" > "Save a copy in Drive". Ini akan membuat salinan notebook di Google Drive Anda.
   #Setelah selesai menggunakan Google Colab, pastikan untuk menutup notebook dan menyimpannya di Google Drive Anda atau unduh dalam format .ipynb.
   